# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(n):
    total = 2
    a = 1
    b = 2
    c = 3
    while (b+c) < n:
        num = b +c
#        print num
        if num % 2 == 0:
            total += num
        a = b
        b = c
        c = a + b
    print total

fib(4000000)
